[build]
  publish = "build"
  command = "npm run build"


[[redirects]]
  from = "/api6"
  to = "http://211.237.50.150:7080/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200